### PR TITLE
 Add dependency information for including in project.

### PR DESCRIPTION
**Pull request by satendrakumar06**
Added dependency information for Maven and SBT so that it is easier for the developers who are new to the library.

### CODE REVIEW

**Comment by retronym** [comment]
Hi @satendrakumar06,

Sorry about the slow response on this PR.

We've actually moved away from including the latest version number in the README because it quite a manual process to update it each release, and it often was out of date.

Instead, we have added the buttons:

image

Which link to a search on the Maven repository. When you click through to a particular version, you get to info for each of the build tools:

image

Unfortunately, this isn't very discoverable. Perhaps we could include some instructions on this process in the README as a compromise? WDYT?

**Comment by satendrakumar06** [comment]
@retronym Thanks for response. 
 I agree it makes sense to not include the exact versions. In order for people to know we can add a line that once you click on the button then you would reach the repo.

**Comment by dlwh** [comment]
FWIW, I was just about to submit a PR doing the exact same thing. Buttons aren't really the default in the community and thus surprising. You also can't cmd-f for them...

**Comment by satendrakumar06** [comment]
@retronym Should I close this pull request ?

**Comment by retronym** [comment]
Sorry about the delay, I'd forgotten about this PR. I've merged it and will figure out a way to keep the version up to date.

**Comment by satendrakumar06** [comment]
@retronym Thanks

**Pull request merged**
