### PR TITLE
Use scala-module-plugin, update tag-based publishing

### PR DESCRIPTION
**Pull request by lrytz**
The build didn't use the `scala-module-plugin` before but duplicated
most of its settings - maybe I missed the reason why this is the case?

Also update tag-based publishing to the latest version.

### CODE REVIEW

**Comment by lrytz** [comment]
Also adds cross-building with 2.13.0-M1

**Comment by SethTisue** [comment]
> The build didn't use the scala-module-plugin before but duplicated
> most of its settings - maybe I missed the reason why this is the case

I am curious about this as well

**Comment by retronym** [comment]
I don't recall the reason. Perhaps I took that across prior to those settings being factored into `scala-module-plugin`. Or perhaps `scala-module-plugin` at the time had some rough edge that prevented direct use. I'll merge and try out the new release mechanism and see what happens.

**Comment by SethTisue** [comment]
released 0.9.6 for 2.13.0-M1: https://travis-ci.org/scala/async/jobs/231268560 (I also closed and released the staging repo on Sonatype)

**Pull request merged**
